import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar.js";
import { DarkmodeContext, DarkmodeProvider } from "./context/DarkmodeContext";
import { DarkmodeButton } from "./components/darkmode/DarkmodeButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkmodeProvider>
          <div >
            <Navbar />
            {children}
            <DarkmodeButton />
          </div>
        </DarkmodeProvider>
      </body>
    </html>
  );
}
